### ISSUE TITLE
Copy from chat context menu does not work

### ISSUE THREAD

**Issue by g4borg** [arbs-io/vscode-openai#149]
If I right click on a chat history, e.g. on a chat bubble, I get a context menu with copy, cut and paste.

Obviously, cut and paste do not work there, but I expected Copy to at least work.

So I assume, this is just an implementation of the underlying control used for implementing the history.

In Linux, the copy works, at least for selected text, in Windows it does not work at all.
Right clicking the bubble without any text selection does not copy anything in both.

What I expected was to copy the whole selected chat bubble (as-is), but I can only do that with selecting and pressing CTRL+C manually.

I can understand, if the context menu cannot be overridden and it is a visual studio code limitation or something similar, to have it present, however, in that case I suggest to add a copy button also to each chat bubble, that copies the entire message (similar to the ones for code examples, maybe in the info button menu?)

If needed I can submit clarifications

**Comment by arbs-io** [comment]
Hi @g4borg 
Many thanks for reporting this issue.
This is a vscode overlay on the webview. Whilst the default context can be controlled, the rendering can't, e.g. context is shown everywhere, even when not over a conversation or message. Therefore I've disabled it for now, and instead, I will add a "Copy Summary" to the conversation dropdown menu. On the message panel the copy work via the keyboard I will see if a custom menu works as excepted if yes will add just a copy menu.

**Comment by arbs-io** [comment]
Hi @g4borg 
I've added the context menu in version 1.4.3 (copy summary and message)
