### ISSUE TITLE
All API requests return "not a valid question"

### ISSUE THREAD

**Issue by lotekjunky** [arbs-io/vscode-openai#150]
I love this plugin and it has become my default way of interacting with OpenAI. I'm back from the weekend and I can't get the plugin to work this morning. I made sure I updated, Linux, Brave, VS Code, and the plugin. Every proompt I feed it returns "not a valid question".  I removed and reinstalled the plugin, created a new API key on openAI, and am still having the same issue. I didn't see anyone else having this issue before, so I figured it was worth a question on here.

**Comment by lotekjunky** [comment]
}    
2023-08-07 13:44:16.603 [info]		embedding_configuration - event properties  
{ max_character_length: '1200', cosine_similarity_threshold: '0.72' }  
2023-08-07 13:44:16.605 [info]		event - scm vscode.git ready  
2023-08-07 13:44:16.633 [info]		event - vscode-openai ready  
2023-08-07 13:44:17.037 [info]		event - verifyApiKey success  
2023-08-07 13:47:06.450 [info]		event - verifyApiKey success  
2023-08-07 13:47:06.454 [info]		setting_configuration - event properties  
{  
  vscode_version: '1.80.1'  ,
  extension_version: '1.4.2',  
  service_provider: 'OpenAI',  
  host: 'api.openai.com',  
  base_url: 'https://api.openai.com/v1',  
  inference_model: 'gpt-3.5-turbo-16k-0613',  
  inference_deploy: 'setup-required',  
  embeddings_model: 'text-embedding-ada-002',  
  embeddings_deploy: 'setup-required',  
  az_api_version: '2023-05-15'  
}  
2023-08-07 13:47:54.127 [info]		chat-completion - event properties  
{  
  service_provider: 'OpenAI',  
  default_model: 'gpt-3.5-turbo-16k-0613',  
  tokens_prompt: '246',  
  tokens_completion: '7',  
  tokens_total: '253',  
  tokens_session: '253'  
}

**Comment by arbs-io** [comment]
Hi @lotekjunky 
Will look into this now. Are you using general chat, persons or resource query? Sound like a message from resource query (from uploaded files)

**Comment by arbs-io** [comment]
I've checked all service providers and models, and I can't see any issue. could you try with vscode-openai instance and see if you get the same response? Also try a simple prompt, something like "where is france"

**Comment by arbs-io** [comment]
Hi @lotekjunky 
Is the issue still persisting?
