### ISSUE TITLE
Availability in VSCodium (Open VSX Registry)

### ISSUE THREAD

**Issue by matccent** [arbs-io/vscode-openai#152]
Could you please publish this extension in [Open VSX Registry,](https://open-vsx.org/) so it's available in VSCodium, please? 

Thank you!

**Comment by arbs-io** [comment]
Hi @matccent 
I would be happy to release to additional market places if there is support for automation. Will need to check how this can be integrated

**Comment by arbs-io** [comment]
Hi @matccent 
The latest version (1.4.3) has been published on the market place
https://open-vsx.org/extension/AndrewButson/vscode-openai
