### ISSUE TITLE
Support custom openai endpoints

### ISSUE THREAD

**Issue by jabbera** [arbs-io/vscode-openai#165]
With the existence of llama.cpp and the openai compatible interface it would be neat if we could point this extension to a custom endpoint as opposed to only the official ones.

**Comment by arbs-io** [comment]
Hi @jabbera 
Could you give me an example. presumably the uri and not the base url is needed. Also is the interface (parameter) the same as native or different?

**Comment by jabbera** [comment]
@arbs-io hi!

Here is some shell code you can use to get one going yourself:

```
export MODEL=llama-2-13b-chat.Q4_0.gguf
if [ ! -f models/${MODEL} ]; then   curl -L https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/${MODEL} -o models/${MODEL}; fi
docker run --rm -it -p 8000:8000 -v ${PWD}/models:/models -e MODEL=/models/${MODEL} ghcr.io/abetlen/llama-cpp-python:latest
```

you can then get to the swagger endpoint with a browser: http://localhost:8000/docs

I've also attached the swagger openapi json (renamed to txt so github will take it) if that is adequate for your ask

[openapi.txt](https://github.com/arbs-io/vscode-openai/files/12643153/openapi.txt)

**Comment by arbs-io** [comment]
Thank @jabbera 
I'll take a look at adding integration for self-hosted models. I've been reviewing the feasibility of running LLMs using rust-wasm, and it looks possible. They could easily be integrated into vscode. But this is arguably a separate project. Once I have a fully functional version, I will OSS and add it to the extension. 
Going to close this enhancement for now as there isn't a feasible solution in the immediate future.
