### ISSUE TITLE
Does not work in `code-server` installation

### ISSUE THREAD

**Issue by iamwavecut** [arbs-io/vscode-openai#166]
It's available to install and looks like it's ready to function after it.

I created a new persona chat.

I write and submit a prompt.

I expect – answer message to appear.

I got – debug window opens showing stats. No answer appears.
```
2023-10-01 23:14:04.109 [info]		event - verifyApiKey success
2023-10-01 23:14:04.110 [info]		setting_configuration - event properties
{
  vscode_version: '1.82.2',
  extension_version: '1.4.5',
  service_provider: 'OpenAI',
  host: 'api.openai.com',
  base_url: 'https://api.openai.com/v1',
  inference_model: 'gpt-3.5-turbo-0613',
  inference_deploy: 'setup-required',
  embeddings_model: 'text-embedding-ada-002',
  embeddings_deploy: 'setup-required',
  az_api_version: '2023-05-15'
}
2023-10-01 23:14:20.345 [info]		chat-completion - event properties
{
  service_provider: 'OpenAI',
  default_model: 'gpt-3.5-turbo-0613',
  tokens_prompt: '305',
  tokens_completion: '214',
  tokens_total: '519',
  tokens_session: '519'
}

```
<img width="332" alt="image" src="https://github.com/arbs-io/vscode-openai/assets/239034/ff61c00f-1f04-42e4-bc8a-73fd51ed3919">

**Comment by arbs-io** [comment]
Hi @iamwavecut 

Does it continuously fail? Or one off? It looks like the request works from the output.

**Comment by arbs-io** [comment]
Hi @iamwavecut 

I don't have the setup required to fix this issue. Are you using vscode.dev or just tunnelling into another dev box? I've made some changes to remove dependencies on nodes which cause issues from the web edition. But there is still an issue with a dependence on os.

Any information on how to setup the environment would be greatly appreciated.

**Comment by iamwavecut** [comment]
Sorry, but I have no way to reproduce it now.

Also, I believe it's a part of a more global issue with 3rd-party server-side VS Code installations, as it affects not only your problem.

You are welcome to close this one.

**Comment by arbs-io** [comment]
Ok, thanks. I'll try and setup the same environment in the future
