### ISSUE TITLE
Allow custom deployments?

### ISSUE THREAD

**Issue by aliozts** [arbs-io/vscode-openai#176]
I don't know if it would be a useful case or easy to implement but, I have deployed codellama using `vLLM` and I found this extension that allows me to change the `model name`, `openai api base`. Is it possible if you can allow custom deployments which does still imitate `openai api` documentation but have different API base and model names other than the ones that are available in openai?

Moreover, can the **format restriction** of openAI API Key be removed, right now I changed it from my command line but if this feature is enabled, other people can use their own API Keys which may or may not follow the openai api key format

**Comment by arbs-io** [comment]
Hi @aliozts 

There have been similar requests before. I will work on the implementation. To help, could you list the exact requirements?
For example
- Allow Additional Security Type (None, ApiKey, Custom)
- Models (if the model list doesn't exist, then allow manual entry of model name)
- ....

**Comment by aliozts** [comment]
Hi @arbs-io  is there anything I can help with by the way? I use Python sadly for this one

**Comment by josetesan** [comment]
Hey, this would make it easier to be integrated for Ollama.ai, for example.

**Comment by arbs-io** [comment]
Sorry for the slow responses. I've got a lot on at the minute. I'll remove the validation and allow manual model entry (if the api doesn't exist). I think this should cover the local instance if they are compatible with openai APIs

**Comment by arbs-io** [comment]
> Hi @arbs-io  is there anything I can help with by the way? I use Python if it's useful

Thanks so much for the offer any and all help is greatly appreciated. Unfortunately python and vscode don't mix well as not all users will have the tollchain installed. But please if you wanted to get involved typescript is a he core language I use. Alternatively rust for some of the wasm features. But you've greatly help with ideas and feature requests. Thanks so much!

**Comment by arbs-io** [comment]
Thanks for the log. 
I've checked everything and can't see any issues with the feature. I've added additional logging if either gitService in vscode can't be found (or is unavailable), and if the git diff hasn't detected any changes. I can't easily check these conditions but can see some clients do have issues when locating the git service/provider. 
The log enhancement will be added to the version 1.5.3 release tomorrow. Could you emulate the issue once the new version has been installed

**Comment by arbs-io** [comment]
Hi @josetesan, @aliozts 
I've added a custom setup. There is still a dependence on openai compatible API., so for Ollama.ai, llama-2 native might not work without a general interrupter.
![image](https://github.com/arbs-io/vscode-openai/assets/71968891/f001fde8-869a-4de6-8fa8-dd9fbd9a04a1)

**Comment by aliozts** [comment]
Hi @arbs-io,  thank you so much for this! I have deployed a Llama-2 model with `vllm` where we can give `EMPTY` as the API key. I can create a configuration without any errors and I can see the settings updated properly but when I try to run

<img width="525" alt="image" src="https://github.com/arbs-io/vscode-openai/assets/36827959/24caae1d-1a12-4028-bc91-c16f2bd86a8a">

I get the respective error. One more question is, is `code completion` available with this extension?

**Comment by arbs-io** [comment]
vllm provides support for the older completion API endpoint. I will add an option for the host to override the API endpoint.
Regarding code completion, I still need to add it. But it wouldn't be difficult. The problem is the "cost" of public services. Sending partial code blocks

**Comment by arbs-io** [comment]
Hi @aliozts 
I can see people successfully use llama-2 and codellama using the custom setup. I presume the host mechanism is using the newer API standard support from openai. I'm going to close as dropping back to completion is not feasible and is flagged as deprecated.
