### ISSUE TITLE
Option to delete Azure API key

### ISSUE THREAD

**Issue by zeeskore** [arbs-io/vscode-openai#180]
Where is the Azure API key stored by the extension?   An option or command to delete an existing API key would be helpful.

**Comment by arbs-io** [comment]
Hi @zeeskore 
The sensitive data is stored in secret storage. It's provided by vscode and is encrypted locally. Only vscode has the key and can only be accessed by the extension that owns it. 

I can add a general reset to remove all setups if that helps?

**Comment by zeeskore** [comment]
Yes, a reset or cleanup would be good.  Thanks.

**Comment by arbs-io** [comment]
reset has been added to 1.4.8
