### ISSUE TITLE
Custom color for chat text

### ISSUE THREAD

**Issue by kavehsfv** [arbs-io/vscode-openai#182]
I was wondering if it would be possible to add a feature that allows users to change the color of the chat text. Currently, the chat text is green, but it would be great if users could choose between blue or white as well. 
Thank you for your time and consideration.

**Comment by arbs-io** [comment]
Great suggestion. I'll get the feature release later today. Code block will be hard to customize. But chat messages should be easy.

**Comment by arbs-io** [comment]
The feature has been added to the latest package (v1.5.1). I'd appreciate a review of the extension marketplace. Many thanks

to use the feature:

Access settings in the conversation menu
![image](https://github.com/arbs-io/vscode-openai/assets/71968891/883f75ff-0318-435c-8255-70bf04c6d856)

The select the color scheme you wish to use:
![image](https://github.com/arbs-io/vscode-openai/assets/71968891/8f8a1b90-9e54-4df2-b060-567417465da3)

**Comment by kavehsfv** [comment]
Works Great, Thank you!

I have another suggestion. Could you please add an option to select a name for each Conversation. 
![image](https://github.com/arbs-io/vscode-openai/assets/17138256/f329f102-da1a-4906-83d4-ec5d849df99d)
It'd be very useful for those people who wants to keep history of chats.
