### ISSUE TITLE
Talk with ChatGPT

### ISSUE THREAD

**Issue by kavehsfv** [arbs-io/vscode-openai#184]
I'm interested in enhancing the functionality of your extension by integrating the newly released Whisper and Text-to-Speech (TTS) APIs. This integration would enable voice interactions with the chatbot, allowing users to input commands through voice and receive audible responses. Implementing Whisper would convert spoken prompts into text, while TTS would vocalize the chatbot's replies.

I understand that incorporating these features may require a significant investment of time and effort. I would greatly appreciate your time for this enhancement.

**Comment by arbs-io** [comment]
Hi @kavehsfv
I've added text to speech using local resource (not the api as azure doesn't support). This will allow the automated read aloud for responses. 
I'll take a look at audio input shortly but I've got a lot at the minute IRL. 
I'll release the update tomorrow version: 1.5.2
