### ISSUE TITLE
Setting to switch Enter & Shift - Enter behaviour

### ISSUE THREAD

**Issue by vipentti** [arbs-io/vscode-openai#187]
First of all, thank you for a great extension.

I have noticed when typing longer messages, especially which contain some formatted text that I want to include it gets tiring to keep pressing shift to include new lines in the message.

Would it be possible to provide a setting for switching the behaviour of Enter and Shift-Enter so that Enter without Shift would write a newline in the message and Shift-Enter would send it?

**Comment by arbs-io** [comment]
Hi @vipentti 
Thanks for the feedback. I will add the option to disable keyboard shortcuts in the editor. It should in the next release.

**Comment by arbs-io** [comment]
This feature will be release in 1.5.3. 
The config option can be accessed by vscode-openai.conversation-configuration.message-shortcuts
you can use the shortcut in the conversation panel
![image](https://github.com/arbs-io/vscode-openai/assets/71968891/3b857f1a-6f96-4dd6-bafd-f746c59c3ada)
