### ISSUE TITLE
Error on Install: Extension 'AndrewButson.vscode-openai' CANNOT use API proposal

### ISSUE THREAD

**Issue by ja-thomas** [arbs-io/vscode-openai#198]
```
2023-12-13 13:52:48.824 [error]		Error: Extension 'AndrewButson.vscode-openai' CANNOT use API proposal: telemetryLogger.Its package.json#enabledApiProposals-property declares: [] but NOT telemetryLogger. The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api AndrewButson.vscode-openai
```

Platform: Windows

VsCode: Version: 1.74.3
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

The extension seems to be installed but calling `vscode-openai.configuration.show.quickpick` results in 

![image](https://github.com/arbs-io/vscode-openai/assets/7561944/887441ed-8506-4d56-89e7-0ae5e58c463a)

Running vscode with the flag mentioned in the error msg does result in the same problems.

**Comment by arbs-io** [comment]
Hi @ja-thomas 
Which version of the extension are you using ? 
What happens when you click the status bar (bottom right)
![image](https://github.com/arbs-io/vscode-openai/assets/71968891/6e4fa950-5a16-4898-afe1-d63d0902d050)

**Comment by ja-thomas** [comment]
it seems that the extension is not installed correctly, I can only see the these prompts, not the Service Provider

![image](https://github.com/arbs-io/vscode-openai/assets/7561944/9b2633cb-83f8-4b29-a92a-76ca771c9613)

**Comment by arbs-io** [comment]
You should have a logo and name in the status bar (bottom right of vscode)

**Comment by arbs-io** [comment]
Hi @ja-thomas 
Please upgrade vscode and the extension. I'm closing as this doesn't seem like a problem with the current extension
