### ISSUE TITLE
Azure OpenAI GPT-4-Turbo - API Version 1106-Preview

### ISSUE THREAD

**Issue by rabbyn** [arbs-io/vscode-openai#208]
Hello @arbs-io , I wanted to update the extension setting to **Azure Open AI GPT-4 Turbo** to get knowledge up to April 2023 as announced by Microsoft [here](https://techcommunity.microsoft.com/t5/ai-azure-ai-services-blog/azure-openai-service-launches-gpt-4-turbo-and-gpt-3-5-turbo-1106/ba-p/3985962) but the **Azure API Version** drop down doesn't provide **1106-Preview**; that's similar to previous issue [here](https://github.com/arbs-io/vscode-openai-docs/issues/13). Thanks for your help

![image](https://github.com/arbs-io/vscode-openai/assets/72968975/9d68d9b9-bbcf-4434-bbbf-c807c96807b6)

![image](https://github.com/arbs-io/vscode-openai/assets/72968975/7b3e535d-f465-4350-b068-7e3b97fca790)

**Comment by arbs-io** [comment]
Hi @rabbyn 
I've been using gpt-4-turbo on azure. The API versions differ from the model/deployment on azure. Currently 2023-05-15 is still the most recent "stable" version of the API and it is compatible with the newest models. Worth noting that gpt-4-turbo is only available is limited locations (sweden, west-us, ...). Do you have the model available in your region?

https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

**Comment by rabbyn** [comment]
Hi @arbs-io , oh ok so this **Azure API Version** in the extension settings has nothing to do with model version ?  my bad I didn't know. it's just that when I asked question about Microsoft Fabric the model doesn't seem to know anything about this subject (which made me thing that despite my change of deployment (name) to **gpt-4-turbo-1106** it was not working properly.

PS: yes my deployment is on Azure Region France Central
![image](https://github.com/arbs-io/vscode-openai/assets/72968975/9ce17850-3f7d-4d85-89ff-aae15ad09e9c)

**Comment by rabbyn** [comment]
no I guess it's fine, the chat is working, I was just expecting the model to answer question about Microsoft Fabric but that's not a big problem, you can close this issue. Thanks
________________________________
