### ISSUE TITLE
Conversations font size

### ISSUE THREAD

**Issue by taro8** [arbs-io/vscode-openai#211]
Would it be possible to add a setting to control the font size for the conversations? My eyesight is not that good.

I know I can enlarge everything in VS Code, with I already do, in addition to making fonts bigger via settings. If I wanted to enlarge it even more, to read conversations, it would clutter the screen too much. So having a control over the font size for the conversation messages would be great.

**Comment by arbs-io** [comment]
Hi @taro8 


Good idea. It's the reason I add test to speech. For the font would you want to control both questions and answers?

**Comment by taro8** [comment]
Yes, both would be good, as well as any code blocks.

Speaking of text to speech, would it be possible to add a button to stop it?

**Comment by taro8** [comment]
Opps, my bad, I closed the issue.

**Comment by apmoore499** [comment]
+1 for more control over the appearance of user interface would be super helpful. on a 4k monitor the font is tiny - here's a screenshot, your extension inside the red box, other windows added for comparison. i can't find anywhere to modify the font size in settings.
![scrn](https://github.com/arbs-io/vscode-openai/assets/61717160/a7c247d4-4503-4bd0-a3c1-a3811b4ce5b4)

**Comment by arbs-io** [comment]
Sorry for the delay. I've been relocating with my family.

If you need a quick access zoom (with I also needed). I created a utility a while ago.

https://marketplace.visualstudio.com/items?itemName=AndrewButson.vscode-source-surge
