### ISSUE TITLE
Generate filenames automatically based on the code

### ISSUE THREAD

**Issue by younes-io** [arbs-io/vscode-openai#212]
It would be great if the extension offered the possibility to name files automatically based on the source code (also with respect to the language used: python, javascript, lua, etc as they would have different styles: camelCase, snake_case, etc)

**Comment by arbs-io** [comment]
Hi @younes-io 
Do you have an example of how you would like this to work? Regarding coding style. This could be achieved by updating the prompt to ask for x standard. If you have any improvements in prompts, I would be extremely grateful.

**Comment by arbs-io** [comment]
bump @younes-io  
Could you provide me with a brief description of how you think this should work?

**Comment by younes-io** [comment]
Sorry for the delay.. I was just wondering if it's possible for the extension (in case of a new file) to propose a few names for it based on the code.. maybe this isn't required by many users, but the other day, I just had this new python file with a few functions, and I didn't know how to name it x) sometimes it's a bit hard to come up with a suitable file name

**Comment by arbs-io** [comment]
Hi @younes-io 
Sorry for the delay. I've tried to implement this feature and it's not that straightforward. The naming works well for services and providers. But for utilities it often gives very long/verbose names which aren't suitable. 
Unfortunately, I don't think I can create a reliable implementation.

**Comment by younes-io** [comment]
@arbs-io: No worries. Do you use any library/tool that constrains the LLM? (the likes of guidance or LMQL)

**Comment by arbs-io** [comment]
LMQL looks really interesting. Currently the dependency is on the openai api spécification. This works for local models with the right host service.
In vscode the internals are js. So only wasm for python compilation or wasm for native LLM. I've been working on the latter recently. If this is achievable then should open up a lot more compatibility.
