### ISSUE TITLE
Multi-window: settings problem, can't use the chosen api

### ISSUE THREAD

**Issue by Madd0g** [arbs-io/vscode-openai#213]
I tried setting a custom local api, it seems like it can only resolve the settings in the active vscode window (I usually have 5+ open)

The one window that opens **first** sees the correct setting and the extension works there, but the rest are showing a message "api.openai.com". Like nothing is configured.

I tried reloading the windows (via the command palette) and I see this behavior where it only works on the focused editor instance but the rest are pointing to the wrong place.

Thanks

**Comment by arbs-io** [comment]
Hi @Madd0g 
Do you mean have 5 vscode windows open? I haven't checked this settings. But if you change the configuration it should update via events.

**Comment by Madd0g** [comment]
I see the configuration is saved, if I go to settings in a window where it doesn't work - I already see the correct settings there

**Comment by arbs-io** [comment]
can you check the logs in output -> vscode-openai.
The setting should be correct. I think it should be the setting at the time of creation. at runtime, the actual current settings are used for subsequent requests. if you could screenshot with the log (please remove any sensitive data)

**Comment by arbs-io** [comment]
I can't re-product this issue. I suspect the sessions are created before the configuration; therefore, the display shows the original service provider. Please re-open and provide more info if the issue persists.
