### ISSUE TITLE
Make git comment prompt configurable

### ISSUE THREAD

**Issue by tcpaddock** [arbs-io/vscode-openai#216]
Pull the git comment prompt from settings similar to other prompts.

**Comment by arbs-io** [comment]
Hi @tcpaddock 
Thanks for requesting the feature. I've added the SCM prompt to the editable prompts 

![image](https://github.com/arbs-io/vscode-openai/assets/71968891/7f91f0a5-4e82-42fe-9c1a-b004e168086b)

The you can simply update the prompt here:

![image](https://github.com/arbs-io/vscode-openai/assets/71968891/0f93b165-7450-4f6c-b46a-a832af81dbf2)

available in version 1.5.8
