### ISSUE TITLE
Feature Request: Streamed code completions in the VS code editor

### ISSUE THREAD

**Issue by lotek4u** [arbs-io/vscode-openai#222]
I realize this is a tall ask, but I looked around and didn't see any other discussions about this feature. I could have missed a previous discussion somewhere, or maybe it's just impossible...

However, I just noticed that an example of streaming completions was recently published by Open AI. Maybe this makes it a possibility, or perhaps not. I but wanted to at least ask so you can give your thoughts on the possibilities.

https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb

Thanks,
Nick

**Comment by arbs-io** [comment]
Hi @lotekjunky 
sorry for the delayed response. I've changed country recently, and that's taken up most of my time.
It's a good suggestion. I want to switch to streaming, but how vscode interacts with webviews makes the implementation tricky. I'll look into this feature and see if it's feasible.

**Comment by arbs-io** [comment]
Hi @lotek4u 
Streaming isn't feasible with the way that vscode and webview work (currently). I've added a response indicator to help know that the request is still being processed.
