### ISSUE TITLE
Feature Request: Chat loading animation in chat winodw

### ISSUE THREAD

**Issue by chrishart0** [arbs-io/vscode-openai#223]
As an end user of VSCODE-OPEN using the Conversations view
I want a clear visual that shows that my chat message is still loading
So that I know I need to continue waiting

Notes:

I do see that at the bottom of VSCode there will be a little loading spinner, but it would be much better UX for the loading spinner, or 3 dots, or whatever to be in the chat window. Example is ChatGPT, when waiting on a message to start streaming, they have a little growing and shrinking dot to let the user know something is going on in the background.

**Comment by arbs-io** [comment]
hi @chrishart0 
sorry for the delayed response. I've changed country recently, and that's taken up most of my time.
It's a good suggestion and I'll take a look and implement a more deliberate waiting status in the chat windows

**Comment by arbs-io** [comment]
Hi @lotek4u 
Streaming isn't feasible with the way that vscode and webview work (currently). I've added a response indicator to help know that the request is still being processed. It's available for version 1.6.4
