### ISSUE TITLE
chat-over-files returns "not a valid question" every time

### ISSUE THREAD

**Issue by paulmikulskis** [arbs-io/vscode-openai#224]
#### Problem Statement

Regular chat with BYOK via Native OpenAI services works fine with a variety of models but **does not work chatting over documents**.

Every response comes back with, _"That is not a valid question"_
The provided OpenAI key has full privileges to the account and all models.

![Screenshot 2024-02-07 at 9 58 39 AM](https://github.com/arbs-io/vscode-openai/assets/16529164/e7865b46-b23a-4c6a-8eac-902e4aa176c3)

#### Observations
Three different embedding models have been tried and selected leading to the same result:
- `text-embedding-3-large`
- `text-embedding-3-small`
- `text-embedding-ada-002`

The behavior is the same across the following OpenAI chat models:
- `gpt-4-1106-preview`
- `gpt-4`
- `gpt-3.5-turbo`

**Runtime Environment**
- Apple M2 on Ventura 13.0 (22A8380)

- Visual Studio Code Version: 1.86.0 
- Visual Studio Code commit hash: `05047486b6df5eb8d44b2ecd70ea3bdf775fd937`
- Visual Studio Code Electron: 27.2.3

- Node.js: 18.17.1

**Plugin Configuration**:
```json
{
  "vscode-openai.serviceProvider": "OpenAI",
  "vscode-openai.baseUrl": "https://api.openai.com/v1",
  "vscode-openai.defaultModel": "gpt-4-1106-preview",
  "vscode-openai.embeddingModel": "text-embedding-3-large",
  "vscode-openai.azureDeployment": "setup-required",
  "vscode-openai.embeddingsDeployment": "setup-required",
  "vscode-openai.azureApiVersion": "2023-05-15",
}
```

**The Logs** 
Logs from each of these chats is the same, showing no error:
```
[info]		chat-completion - event properties
{
  "service_provider": "OpenAI",
  "default_model": "gpt-4-1106-preview",
  "tokens_prompt": "250",
  "tokens_completion": "7",
  "tokens_total": "257",
  "tokens_session": "1022"
}
```

---

An additional related bug to document chat is that upon clicking the 🗑️ icon next to a file, the file **will not** be removed from the roster.

![Screenshot 2024-02-07 at 10 03 50 AM](https://github.com/arbs-io/vscode-openai/assets/16529164/50f0b4c0-77a4-4f98-9cac-4176595a51e0)

**Comment by arbs-io** [comment]
Hi @paulmikulskis 
Thanks for reporting. I will take a look into the issues

**Comment by arbs-io** [comment]
Sorry for the delay.

The query resource is for embedding. This chunks the data and performs a similarly check (this approach is now known as RAG). It will not work on source code as it's designed for natural language. For example uploading specification, code standards or reference books.

I will add a and to chat feature for source code soon. This will help achieve the functionality you're looking for.
