### ISSUE TITLE
Error with uploading sources

### ISSUE THREAD

**Issue by dv0zn3r** [arbs-io/vscode-openai#225]
I am encountering an error every time I upload a source. 

The specific error message I am receiving is:

```bash
 [info]		file_information - event properties

{
  "path": "/Users/../example.txt",
  "extension": "txt",
  "mimetype": "text/plain",
  "length": "69195"
}

[error] EntryNotFound (FileSystemError): Unable to read file 'vscode-userdata: 
Users/../Library/Application Support/Code/User/globalStorage/andrewbutson.vscode-openai/embedding.v2-1ea4ae7a-f021-4751-98e6-fb1083b6c007' 
(Error: Unable to resolve nonexistent file 'vscode-userdata:/Users/../Library/Application Support/Code/User/globalStorage/andrewbutson.vscode-openai/embedding.v2-1ea4ae7a-f021-4751-98e6-fb1083b6c007')
```

My current settings:

```json
{ "vscode-openai.serviceProvider": "OpenAI",
    "vscode-openai.baseUrl": "https://api.openai.com/v1",
    "vscode-openai.defaultModel": "gpt-4-turbo-preview",
    "vscode-openai.embeddingModel": "text-embedding-3-small",
    "vscode-openai.azureDeployment": "setup-required",
    "vscode-openai.embeddingsDeployment": "setup-required",
    "vscode-openai.azureApiVersion": "2023-05-15",
    "vscode-openai.embedding-configuration.max-character-length": 1024
}
```

**Comment by arbs-io** [comment]
hi @dv0zn3r 
sorry for the delayed response. I've changed country recently, and that's taken up most of my time.
are you uploading via Explorer (or another Windows interface) or via vscode directly? It looks like the chucking is working as expected.

**Comment by TimKoenigIFF** [comment]
Hi, I get the same error for the first source file uploaded even though the embedding file exists. 

However, if I then upload another source file (or the same file again) no more embedding files will be created in the directory.

**Comment by TimKoenigIFF** [comment]
I found out that you have to index a selected directory first and afterwards the indexing of selected individual files works as well.

However, if you do not select a directory and try to index individual files first, the above-mentioned error message appears in my case.

**Comment by arbs-io** [comment]
Are you still seeing the error? I've made various changes to the resource provider and can't replicate the issue

**Comment by arbs-io** [comment]
Closing as I can't replicate the issue
