### ISSUE TITLE
Chat does not provide any answer

### ISSUE THREAD

**Issue by markusheimerl** [arbs-io/vscode-openai#226]
![image](https://github.com/arbs-io/vscode-openai/assets/149831926/859fa221-a568-4d62-82d2-65c4ed841c19)
Generating commit messages works though

**Comment by markusheimerl** [comment]
![image](https://github.com/arbs-io/vscode-openai/assets/149831926/977b7fbe-1238-4086-b9c6-039b587a03cc)
According to the log everything went fine.
I am using a vscode server tunnel to my GPU cloud machine. Could that maybe be a problem? (https://code.visualstudio.com/docs/remote/tunnels)

**Comment by arbs-io** [comment]
Hi @markusheimerl 
I think this is an issue with context. Will take a look at scenarios that could cause this

**Comment by arbs-io** [comment]
i could replicate this issue but i don't have a cloud machine. I suspect it's an issue with vscode internally
