### ISSUE TITLE
Unable to paste into the dialog box

### ISSUE THREAD

**Issue by lacostenycoder** [arbs-io/vscode-openai#228]
Since the extension can't read my code, not being able to at least paste code into the chat box renders this plugin useless.  I'm running Windows 10 with WSL2 Ubuntu.

**Comment by arbs-io** [comment]
Hi @lacostenycoder 
Can you please provide a screenshot and the log file. I've not seen code editor not working on any environment

**Comment by arbs-io** [comment]
Just to note that openai uses Markdown as a standard and therefore so does the rendering 
In markdown syntax is (example for Typescript)

Normal message for the prompt
'''ts
<some code>
'''

**Comment by arbs-io** [comment]
Fix explained, no response
