### ISSUE TITLE
Feature Request: Chat with AI about your code

### ISSUE THREAD

**Issue by sXperfect** [arbs-io/vscode-openai#229]
I hope `vscode-openai` will have a feature similar to [twinny](https://github.com/rjmacarthy/twinny) where you can highlight your code and chat with the AI using the code as context.

**Comment by arbs-io** [comment]
Hi @sXperfect 
Good suggestion. Technically the context menu works on selected code already. I will add a send to chat feature

**Comment by arbs-io** [comment]
Going to close as I'm working with a few SLM on this functionality. The requirements for request in LLM make this very expensive to run. Will post back with more info soon
