### ISSUE TITLE
Error: Activating extension 'AndrewButson.vscode-openai' failed: ENOENT: no such file or directory, open '\out\asset-extractor-wasm_bg.wasm'

### ISSUE THREAD

**Issue by HarSingh22** [arbs-io/vscode-openai#232]
I cloned this repo and tried to run this extension. After I did npm i and I cannot see asset-extractor-wasm_bg.wasm file in out folder and it's giving me below error when I try to build this extension.

Can you please let me know if I am doing something wrong ? Thank you.

**Comment by arbs-io** [comment]
The extension has multiple projects.
Can you run:
npm run install:all
npm run build:all

Would appreciate any enhancement PRs on the project
