### ISSUE TITLE
Integration with Predibase

### ISSUE THREAD

**Issue by gyanesh-mishra** [arbs-io/vscode-openai#233]
Hello,

I am trying to use this plugin with a dedicated LLM that I have running on Predibase. The service is OpenAPI compatible and I am able to use it with the openAI SDK.

Docs:
https://docs.predibase.com/user-guide/inference/migrate-openai

I can prompt it [using curl](https://docs.predibase.com/user-guide/inference/migrate-openai#rest-api-example) as well.

However when I try to use the extension with the following configs, I see 404s.
```
{
    "vscode-openai.baseUrl": " https://serving.app.predibase.com/TENANT_CODE/deployments/v2/llms/mistral-7b-instruct/v1/chat/completions",
    "vscode-openai.defaultModel": "setup-required",
    "vscode-openai.embeddingModel": "setup-required",
    "vscode-openai.azureDeployment": "setup-required",
    "vscode-openai.embeddingsDeployment": "setup-required",
    "vscode-openai.azureApiVersion": "2023-05-15",
    "vscode-openai.conversation-configuration.assistant-rules": false,
    "vscode-openai.conversation-configuration.api-headers": [
        {"Content-Type": "application/json"},
        {"Authorization": "Bearer AUTH_TOKEN"},
    ],
    "vscode-openai.serviceProvider": "Custom-OpenAI",
}
```

Is there a way to log the network requests or see verbose information on what's going on?

Thank you!

**Comment by arbs-io** [comment]
Hi @gyanesh-mishra 
You should be able to configure local LLMs using the custom type. This provides a raw pass through to work with local models. 
The local model must support chat completion and not just completion endpoints.

**Comment by gyanesh-mishra** [comment]
@arbs-io Thank you for responding 🙏 
I'm trying the "custom" approach as you can see from my vscode config above.

Can you link me to the chat completion you're mentioning here? AFAIK the custom LLM API supports `/chat/completions` endpoint.

Is there a way for me to see what endpoing and the raw query looks like before the plugin makes it?

**Comment by noyoshi** [comment]
Looks like the issue is that Predibase would need to support the `URL/v1/models/versions/name/<model_name>` endpoint? 

I was able to get the chat/completions requests to go through by using `https://serving.app.predibase.com/TENANT_CODE/deployments/v2/llms/mistral-7b-instruct/v1` as the base URL though, but the request ended up failing due to the first endpoint not existing

**Comment by noyoshi** [comment]
Interesting, so leaving the model name blank instead of two quotes results in a new error. Looks like github.com/predibase/lorax does not support "system" roles in the chat completions API. Going to raise an issue there and look into it.

**Comment by noyoshi** [comment]
Looks like its an issue with the model - llama and mistral aren't trained to allow "system" roles for chat completions. 

Models like zephyr are, and using that worked!

**Comment by arbs-io** [comment]
Hi @noyoshi 

Thanks for validating the custom models. I can't support all variations so very good to hear there are models that are compatible with OpenAI API
