### ISSUE TITLE
Certificate has expired?

### ISSUE THREAD

**Issue by Tanooki907** [arbs-io/vscode-openai#236]
Hello,

I have encountered a problem where I cannot even begin to use the extension.

When VSCode first opens, I get the following error in the console: **Error: 401 Your authentication token is not from a valid issuer.**

So I tried to go through the initial setup process and reconnect to my GitHub account, but as I do so, I get a message about how my 'certificate has expired'. I'm not sure what to do - the extension worked absolutely fine up to this point, but I can't even get a response now.

How do I get the extension to accept my GitHub account again?

Thank you!

**Comment by arbs-io** [comment]
Can you try and sign out from vscode and then sign in again 

![image](https://github.com/arbs-io/vscode-openai/assets/71968891/d5303d61-c7cc-4514-88ef-e6ddaaaf8c47)

**Comment by koyoungmin123** [comment]
I also see the same message. I cannot solve this matter. Somebody helf me... plz.

**Comment by Tanooki907** [comment]
> Can you try and sign out from vscode and then sign in again
> 
> ![image](https://private-user-images.githubusercontent.com/71968891/321991391-d5303d61-c7cc-4514-88ef-e6ddaaaf8c47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5NjI1NTgsIm5iZiI6MTcxMjk2MjI1OCwicGF0aCI6Ii83MTk2ODg5MS8zMjE5OTEzOTEtZDUzMDNkNjEtYzdjYy00NTE0LTg4ZWYtZTZkZGFhYWY4YzQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDIyNTA1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MDYzNjkzZTk5ZGFlMTkyYTVlOTkyZjEzZWNkNTVkMzQ2Y2FkZjQ4MDNjNjRlY2I5MGJlMmE0NWUzYjdjNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ht0Klsxwkt0UC-8cGVCqJ26wISfIab5EEz-ONy9dHVk)

Thank you for reaching out! I tried your suggestion, but I got the same end result. I'm not sure what's going on.

Are there any other courses of action you might suggest?

**Comment by koyoungmin123** [comment]
I tried that new install in other system. But occured same matter. How can I solve it.....

**Comment by rverheijen** [comment]
Hi, hitting the same problem. I was wondering if this all relates to using the (Sponsored) vscode-openai service and what base_url you are using? Thx

**Comment by Tanooki907** [comment]
Yes, I am using the sponsored service. As for a base_url, I don't recall having to concern myself with that - I've never been asked about a base_url by the extension.

**Comment by arbs-io** [comment]
Apologies for the delayed response. I will verify the cert on the gateway this evening.

**Comment by arbs-io** [comment]
the issue has now been resolved. apologies for the delays

**Comment by koyoungmin123** [comment]
Now properly worked.. tks your good action.
