### ISSUE TITLE
SSO/AD login for Azure Open AI

### ISSUE THREAD

**Issue by shrijit-narkar** [arbs-io/vscode-openai#246]
Currently we are need to pass APIKey to login to Azure Open AI. Can we have functionality to use AD as the login authentication for Azure? The reason is we do not want to provide the ApiKey key to all the developers. But we can provide them permission to Azure Open AI service in Azure Portal.

**Comment by arbs-io** [comment]
Great suggestion and one that would be useful for enterprises using api gateway. I will add functionality to configure oauth2 rather than api key

**Comment by arbs-io** [comment]
@shrijit-narkar 
oauth2 is now enabled for the azure service (v1.6.6).
