### ISSUE TITLE
gpt4o model

### ISSUE THREAD

**Issue by eolamisan** [arbs-io/vscode-openai#249]
azure open ai gpt4o model does not show in the list.

will it be supported?

**Comment by Lennart01** [comment]
gpt4o follows the official openai API spec.
https://platform.openai.com/docs/api-reference/chat/create
This should work out of the box

**Comment by eolamisan** [comment]
Does is matter that I'm using the model from openai.azure.com? 
It does not appear in the list of models.
The model was deployed yesterday.

**Comment by Lennart01** [comment]
No.
The only thing you would need to change is the Azure Deployment name (assuming you have an azure openai serverice)

**Comment by eolamisan** [comment]
Manually updating settings worked. Just the extension configuration UI doesn't show the model.

**Comment by arbs-io** [comment]
@Lennart01 Thanks so much for helping out! Truly appreciated

@eolamisan let me validate this over the weekend. It should be automatically list if the deployment is available on azure. It might be a cache issue if the deployment was made after the model/deployment have been made.

**Comment by arbs-io** [comment]
i've fixed the issues in 1.6.2
This is a workaround because Microsoft has not continued support for the standard deployment listing. but the gpt-4o should work
