### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by adamoutler** [arbs-io/vscode-openai#251]
Whenever I open the app and then try to send a message I get a type error. I've
1. installed the extension
2. provided my API key
3. had a normal conversation
4. Attempted to have a conversation about my workspace files and observed the typeerror below
```
2024-05-27 20:23:32.298 [info]		event - vscode-openai ready
2024-05-27 20:23:34.504 [info]		event - verifyApiKey success
2024-05-27 20:26:28.855 [error]		TypeError: Cannot read properties of undefined (reading 'reduce')
```
this occurs every time I try to converse on my repository.

**Comment by arbs-io** [comment]
Hi @adamoutler 
Are you still getting this error? I can't reproduce.

**Comment by arbs-io** [comment]
please reopen if issue persists and include more info on the environment and log trace

**Comment by trifestone** [comment]
I had the same error when i queried resources, and with vscode debug i found out the point, in the function 'searchFileChunks', var 'chunk's member 'embedding' was undefined, that led to this Error, but actually, i didn't konw how to fix it.
<img width="1666" alt="image" src="https://github.com/user-attachments/assets/e08aa8e7-86bd-4cf4-b11b-895d6e46559c">
