### ISSUE TITLE
Specifying max_tokens

### ISSUE THREAD

**Issue by treyd** [arbs-io/vscode-openai#252]
I am trying to use a custom LLM endpoint with a custom model that is openai-api compatible.  However, to use this endpoint, I need to set `max_tokens` to `1024`.  Otherwise, I will only get 16 tokens back.  Is there a way to set this in the extension for a custom endpoint?

**Comment by arbs-io** [comment]
Hi @treyd
the max_tokens parameters is now available in 1.6.4
