### ISSUE TITLE
Error loading webview: error: could not register service worker: invalid state error: failed to register a serviceworker: the document is in an invalid state

### ISSUE THREAD

**Issue by eolamisan** [arbs-io/vscode-openai#257]
Getting this week this error message and the chat box does not open.

![image](https://github.com/arbs-io/vscode-openai/assets/4191912/ca90369a-236a-4ca3-815c-6b0e531bcfa9)

This error message could be related "Azure DeploymentModels not found (requires: gpt-3.5 and above)"

**Comment by arbs-io** [comment]
Hi @eolamisan 
Could you reset and re-run the setup? It looks like the extension has the wrong deployment name, have you upgraded the model or created a new deployment on your instance

**Comment by eolamisan** [comment]
Hi,

Reset has helped.

Though, the model deployment has not changed and I have been using it ever since gpt-4o came out successfully until this week.

Best,
Edward
________________________________

**Comment by arbs-io** [comment]
This seems to be a problem with vscode. Could you killall / task-manager kill all processes of vscode.

Then clear the cache for vscode (it will rehydrate went you reopen) 

```bash

# close vscode instances (make sure no process is running)

# Linux
rm -rf ~/.config/Code/Cache

# macOS
rm -rf ~/Library/Application Support/Code/Cache

# Windows PowerShell
Get-ChildItem "$env:APPDATA\code" -Directory -Filter Cache -Recurse | Remove-Item -Force -Recurse

# Windows Command Prompt (cmd.exe)
rd /s /q "%APPDATA%\Code\Cache"
```
