### ISSUE TITLE
Complete feature for working on code

### ISSUE THREAD

**Issue by onknows** [arbs-io/vscode-openai#263]
Add a "Complete" feature that will use AI to complete a code file. The prompt will read TODO comments in the file and make code changes to the file based on those comments.

Maybe the Bug Bounty, Comments can be fully customizable features? Where you can also for example configure the type of feature where the feature can change the code, offer code changes via clipboard as with optimize etc.

**Comment by arbs-io** [comment]
Hi @onknows 
you can customise the prompt. To achieve the above you need to add your instructions to the prompt via settings. 

Closing as i don't think this requires development 

![image](https://github.com/user-attachments/assets/11f0677d-1513-4d11-86df-a11285fcf025)
