### ISSUE TITLE
Chat window in sidebar or a popup? 

### ISSUE THREAD

**Issue by chris-trag** [arbs-io/vscode-openai#275]
Any tips on how I can get the chat dialog to be in the sidebar or in it's own pop-window separate of the code editor? 
<img width="846" alt="image" src="https://github.com/user-attachments/assets/7e9fdde3-07b0-4a16-adf2-ffed1b0009dc">

**Comment by arbs-io** [comment]
hi @chris-trag 

which version of vscode do you have? could you upgrade to the latest +1.91.0. Older versions have limited support for popups. Closing as i can't replicate on newer verison (mac, lnx or win)

**Comment by arbs-io** [comment]
here is the example of a popout on windows 1.91.0

![image](https://github.com/user-attachments/assets/83bb6156-fc8d-4f52-aea6-2ecbb756b582)
