### ISSUE TITLE
Streaming for chat completion

### ISSUE THREAD

**Issue by iranogajec** [arbs-io/vscode-openai#280]
It would be great to add chat streaming to aviod waiting for the entire answer to finish before it is visible.

**Comment by arbs-io** [comment]
Hi @iranogajec 
This has been added to v1.6.8

**Comment by kavehsfv** [comment]
Hi, is there any setting line for active or deactivate the streaming?

**Comment by arbs-io** [comment]
It tries to stream, if the model/api doesn't support e.g. previews. The extension switch over to non-stream mode.
Do you want to manually control this?

**Comment by schttrj** [comment]
> It tries to stream, if the model/api doesn't support e.g. previews. The extension switch over to non-stream mode. Do you want to manually control this?

the instance that I use doesn't support streaming. that's why I see blank responses (perhaps?). how do I disable it?
