### ISSUE TITLE
Feature request: Add button to add create new persona and customize quick access tool

### ISSUE THREAD

**Issue by wasawatpeng** [arbs-io/vscode-openai#284]
I hope I can add the new persona and save it to the extension 'Customize prompt' feature but can add more than one and save it as one of the persona template. Also the same function for the quick access tool.

**Comment by arbs-io** [comment]
Hi @wasawatpeng 
You can edit the existing persona via options. This way you can fully customize each persona.

**Comment by arbs-io** [comment]
Closing as all persons are customizable. You need to use settings in vscode
