### ISSUE TITLE
Feature request: Add option to save messages

### ISSUE THREAD

**Issue by kavehsfv** [arbs-io/vscode-openai#297]
Hi,

Could you please add a feature for saving messages? Sometimes, I find it challenging to locate a specific received message and have to scroll through the chat history to find it. It would be great to have a dedicated chat history for saved messages. 

Thank you!

**Comment by arbs-io** [comment]
Hi @kavehsfv 
Do you want a search feature over conversation history?

**Comment by arbs-io** [comment]
@kavehsfv you can search message using Ctrl+F which show a standard Find dialogue.

**Comment by kavehsfv** [comment]
Hi,

No, I don't need the search a message in a conversation. Some messages in conversation with the LLM model are temporary, but some messages are worth keeping to review again in the future. I was wondering if you could add a save option to keep them forever. The following image shows an example:

![Presentation8](https://github.com/user-attachments/assets/505a9650-7361-4be8-a96d-56ba009d4f8a)


thanks.

**Comment by arbs-io** [comment]
The conversation (complete) are saved by default. Are you trying to save/index specific messages?

**Comment by kavehsfv** [comment]
Exactly, It would be great if we can save a specific message in a conversation. 
All saved messages (from different conversations) are in one 'Saved Messages' conversation. Like the messaging apps (Telegram or WhatsApp)

Thanks for your consideration.
