### ISSUE TITLE
Actively monitoring the terminal prompts

### ISSUE THREAD

**Issue by EnochSojourn** [arbs-io/vscode-openai#300]
I'm curious if there has been any consideration of actively monitoring the terminal prompts to help open AI debug code?

**Comment by arbs-io** [comment]
Hi @EnochSojourn 
Thanks for raising. I have tried to implement the feature and it's much harder than expected. It's not difficult for a single "known" language e.g. the compiler, runtime, linker and debuggers are known. But given the variation the solution became very complex. perhaps i will release the solution for typescript, python and rust as they all differ.
