### ISSUE TITLE
Version 1.6.12 Is Missing Menu Editor Icon

### ISSUE THREAD

**Issue by MackeyK24** [arbs-io/vscode-openai#308]
In the latest build the OpenAI Icon that was on the tab bar is now missing. So now the only way to invoke the following items if from the ... drop down:

Bug Bounty
Comments
Design Patterns
Explanation
Optimize

<img width="456" alt="Screenshot 2024-10-25 at 5 27 34 AM" src="https://github.com/user-attachments/assets/bb5c0dc0-891c-4607-86df-3e397131626a">

Previous Version 1.6.11

<img width="419" alt="Screenshot 2024-10-25 at 5 31 16 AM" src="https://github.com/user-attachments/assets/b451f781-f640-4769-b6d4-a9be0bff522e">

**Comment by MackeyK24** [comment]
As workaround i renamed:

```
vscode-openai.menu.editor
```

back to:

```
vscode-openai.menu.toolbox
```

And icon has returned, yeah :)

**Comment by MackeyK24** [comment]
Kool, you fixed it too

**Comment by arbs-io** [comment]
I was about to respond; the last version has the fix. truly  sorry for missing this with the previous release
