### ISSUE TITLE
missing "Edit conversation details" to update the name of a conversation

### ISSUE THREAD

**Issue by robertodijo** [arbs-io/vscode-openai#312]
When I start a new conversation I am getting the message: You can change the conversation name in VSCODE-OPENAI by clicking on the three dots menu in the top right corner of the chat window, then select "Edit conversation details" and update the name to your preference.

However, I don't see this option under the 3-dots of the chat window.

**Comment by arbs-io** [comment]
there is a context windows with options but renaming isn't currently an option. Which version are you using?
