### ISSUE TITLE
Issue when copy-pasting parts of code 

### ISSUE THREAD

**Issue by andreashogberg** [arbs-io/vscode-openai#313]
When copying only a selection of a given response it creates line breaks after every single word or special character.

What i copy:
![image](https://github.com/user-attachments/assets/ff45f513-38e4-471a-8895-6b65a754df6f)

What gets pasted:
![image](https://github.com/user-attachments/assets/9920c62c-61e8-420b-b12e-ad22696405ba)

If i use the "Copy" button to copy the entire text then it works as expected.
If i use the "Open" button to get the snippet in the editor itself it works as expected.
Only when copying a segment from a given response does it create new line breaks

**Comment by arbs-io** [comment]
sorry for the slow response. this issue has been resolve and will be packaged in the next release

**Comment by arbs-io** [comment]
this has been resolve in 1.6.14
